### PR TITLE
bump version to 12.19.0

### PR DESCRIPTION
**Pull request by themightychris**
Is this the right form for commit messages post-spinout?

### CODE REVIEW

**Comment by MindNumbing** [comment]
Hey @themightychris, We haven't settled on a commit message format. General change notes are good.

**Comment by themightychris** [comment]
The check failure does not appear to be connected to the changes contained in this PR, correct?

**Comment by MindNumbing** [comment]
It looks to be caused by our pipeline not working on a fork. We'll look onto it.

**Comment by themightychris** [comment]
@MindNumbing should I bump this to 12.19.0? Is there a way yet to move forward towards getting `core/node12` updated?

**Comment by predominant** [comment]
@themightychris I'd love to help, but the azure pipielines build cannot be found.

**Comment by mwrock** [comment]
closing in favor of #5

**Pull request closed without merging**
